Skip authentication for the `OIDCKeycloak.js` file (Fix regression)
eclipse-che/che pull request #9505
Opened 2018-04-20 10:21 UTC by davidfestal

### What does this PR do?

This PR fixes a regression found while working on issue https://github.com/redhat-developer/rh-che/issues/632

It appears that commit https://github.com/eclipse/che/commit/38ff5c084b5901960cc8825894e0677dd2ba93a7 broke the support of alternate OIDC providers by restricting access to the `api/keycloak/OIDCKeycloak.js` file.

### What issues does this PR fix or reference?

This PR is required in the context of issue https://github.com/redhat-developer/rh-che/issues/632

2018-04-20 10:32 UTC, akorneta approved these changes

2018-04-20 10:39 UTC, davidfestal commented
ci-test

2018-04-20 11:36 UTC, garagatyi approved these changes

2018-04-20 11:37 UTC, garagatyi requested changes
Please, add unit tests that would prevent breaking this again.

2018-04-20 11:49 UTC, l0rd approved these changes

2018-04-20 16:18 UTC, davidfestal commented
> Please, add unit tests that would prevent breaking this again.

@garagatyi done in commit https://github.com/eclipse/che/pull/9505/commits/8c66a545a4fb4efc9b5a7459c280bea4b376e766

2018-04-23 08:21 UTC, garagatyi approved these changes

2018-04-23 08:23 UTC, merged